global:
  pattern: ai-quickstart-rag
  device: cpu # one of 'cpu' (no GPU) or 'gpu' (NVIDIA GPU)
main:
  clusterGroupName: prod
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
